### PR TITLE
corrections to part related to docker

### PR DESCRIPTION
**Pull request by gertingold**
When trying to use ``envkernel`` with a ``docker`` image for grading in ``nbgrader`` (cf. jupyter/nbgrader#483) I ran into a few problems caused by what I think are errors in the code. This PR attempts to rectify these problems.

While I think that the changes make sense, they should be carefully checked as I have very little experience with ``docker`` and might have misunderstood something. Anyway, I hope that this PR helps to improve ``envkernel`` as it looks like a promising way to cope with a security issue in ``nbgrader``.

### CODE REVIEW

**Comment by rkdarst** [comment]
Thanks!  Our first ever NordicHPC pull request.

I think it looks good.  The docker code had never been tested in its current form (copied from a previous iteration of envkernel), so I was sure it wouldn't work as-is.  If it works for you, great.  I'd say just keep iterating on it to fix whatever problems you may find and keep sending the fixes here.

Some design notes that may not be documented:

- Previous iterations parsed options and re-formatted them in docker format, now I try to pass through stuff as unchanged as possible.
- A previous iteration did some weird stuff with bind-mounting directories: to handle our kerberos filesystem there was an option to copy bind-mounted directories to a temporary location before actually using it.  I think maybe this could be commented out now, fix everything else, and then re-add it.  Or not if it's OK as is.  The bind-mount substitution of {workdir} may still be useful.
-  Also you could improve readme and comments if you see things that help.

Now that you've provided incentive I'll probably make a pass in a few days too.

Thanks a lot for the contribution!

**Comment by gertingold** [comment]
Thanks a lot, @rkdarst, for providing ``envkernel``. I just got it to work with ``nbgrader`` and a ``docker`` image. So far, everything seems to work fine.  If I should come up with additional fixes, I will be happy to send them.

**Comment by rkdarst** [comment]
Would you say that any improvement in documentation is needed?  If you let me know I can work on it.

**Comment by gertingold** [comment]
I guess that at some point, the docker section deserves to be updated and (may be) brought to the same level of detail as the section on singularity. On the other hand, I was able to get the docker setup running with the present documentation, so probably, changes are not that urgent. Actually, I was wondering whether a coherent text for the use with ``nbgrader`` would be useful. All necessary pieces seem already to be present either in your README or in your comments in jupyter/nbgrader#483, but some people might appreciate to have everything in one place.  I guess that @jhamrick should decide whether she would like to see a text on ``envkernel`` and ``nbgrader`` in her docs. She might respond to a corresponding remark which I made in jupyter/nbgrader#483.

As a side remark, I would like to mention that while I got ``envkernel`` to work with ``nbgrader`` in a teacher-student setup on my laptop, I encountered problems in my production setup. The reason is that ``jupyter`` does not get the environment variable ``XDG_RUNTIME_DIR`` of the user before constructing ``connection_file``. As far as I can tell, ``envkernel`` cannot do anything about this as it enters the stage only after ``{connection_file}`` has been expanded. So, depending on the setup used, there might still be some problems to be solved.

**Pull request merged**
